-- RegWatch Compliance Rules Seed Data
-- Australian regulatory deadlines for small businesses

-- Taxation obligations
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('BAS / GST Lodgement (Quarterly)', 'Lodge your Business Activity Statement and pay GST collected. Required if registered for GST (turnover over $75,000).', 'taxation', 'quarterly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', '28th of month after quarter end', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst'),
  ('BAS / GST Lodgement (Monthly)', 'Lodge your Business Activity Statement and pay GST collected monthly. Required if turnover exceeds $20 million or voluntarily elected.', 'taxation', 'monthly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', '21st of following month', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst'),
  ('Income Tax Return', 'Lodge your annual income tax return. Due dates vary by entity type.', 'taxation', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', '31 October', 'Australian Taxation Office', 'https://www.ato.gov.au/individuals-and-families/your-tax-return/how-to-lodge-your-tax-return/lodge-your-tax-return'),
  ('Company Tax Return', 'Lodge your company tax return with ASIC and pay any tax owing.', 'taxation', 'annually', ARRAY['company'], '{}', '{}', '15 May (self-preparer) or 5 June (tax agent)', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/corporate-tax-payments-and-assessment'),
  ('PAYG Withholding', 'Withhold tax from employee wages and report to ATO via Single Touch Payroll.', 'taxation', 'monthly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', '21st of following month', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/payg-withholding'),
  ('Single Touch Payroll Reporting', 'Report payroll information to ATO each time you pay your employees.', 'taxation', 'weekly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Each pay cycle', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/paying-your-employees/single-touch-payroll'),
  ('PAYG Instalments', 'Pay quarterly instalments towards expected annual income tax liability.', 'taxation', 'quarterly', ARRAY['sole_trader', 'partnership', 'company', 'trust'], '{}', '{}', '28th of month after quarter end', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/payg-instalments'),
  ('Fringe Benefits Tax Return', 'Lodge FBT return if you provide fringe benefits to employees.', 'taxation', 'annually', ARRAY['company', 'trust', 'partnership'], '{}', '{}', '21 May', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/fringe-benefits-tax');

-- Employment obligations
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Superannuation Guarantee Payments', 'Pay superannuation contributions for eligible employees (currently 11.5%). Must use SuperStream.', 'employment', 'quarterly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', '28th of month after quarter end', 'Australian Taxation Office', 'https://www.ato.gov.au/businesses-and-organisations/super-for-employers'),
  ('Workers Compensation Insurance', 'Maintain workers compensation insurance for all employees. Requirements vary by state.', 'employment', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Renewal date based on policy', 'State WorkCover Authority', NULL),
  ('Fair Work Information Statement', 'Provide new employees with the Fair Work Information Statement before or as soon as practicable after they start.', 'employment', 'once', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Upon commencement', 'Fair Work Ombudsman', 'https://www.fairwork.gov.au/employee-conditions/national-employment-standards'),
  ('Modern Award Compliance', 'Ensure you are paying correct wages, penalties, and entitlements under applicable Modern Awards.', 'employment', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Review annually', 'Fair Work Ombudsman', 'https://www.fairwork.gov.au/pay-and-wages/minimum-wages');

-- Safety & WHS
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Work Health & Safety Policy', 'Develop and maintain a WHS policy. Review annually and ensure all workers are aware.', 'safety', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Review annually', 'Safe Work Australia', 'https://www.safeworkaustralia.gov.au/whs'),
  ('Workers Compensation Claims Reporting', 'Report workplace injuries to your workers compensation insurer within required timeframes.', 'safety', 'once', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Within 48 hours of becoming aware', 'State WorkCover Authority', NULL),
  ('SWMS (Safe Work Method Statements)', 'Prepare SWMS for high-risk construction work before commencing.', 'safety', 'once', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['construction'], 'Before work commences', 'Safe Work Australia', 'https://www.safeworkaustralia.gov.au/swms'),
  ('Emergency Plan Review', 'Review and update your emergency plan, including evacuation procedures.', 'safety', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Review annually', 'Safe Work Australia', 'https://www.safeworkaustralia.gov.au/emergency-plans');

-- Environmental
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('EPA Licence Renewal', 'Renew your Environment Protection Authority licence if your business conducts licensable activities.', 'environmental', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['manufacturing', 'construction', 'transport', 'agriculture'], 'Based on licence conditions', 'State EPA', NULL),
  ('Waste Disposal Compliance', 'Ensure hazardous and regulated waste is disposed of through licensed contractors.', 'environmental', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['manufacturing', 'healthcare', 'construction', 'hospitality'], 'Ongoing compliance', 'State EPA', NULL);

-- Consumer Protection
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Australian Consumer Law Compliance', 'Ensure products and services comply with Australian Consumer Law, including refund policies, warranties, and product safety.', 'consumer', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['retail', 'hospitality', 'professional_services', 'technology'], 'Ongoing compliance', 'ACCC', 'https://www.accc.gov.au/business/advertising-and-promotions'),
  ('Product Safety Recalls', 'Monitor and action any product safety recalls or mandatory standards that apply to your products.', 'consumer', 'monthly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['retail', 'manufacturing'], 'Ongoing monitoring', 'ACCC Product Safety', 'https://www.productsafety.gov.au/');

-- Financial
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Annual Financial Statements', 'Prepare annual financial statements. Companies must lodge with ASIC.', 'financial', 'annually', ARRAY['company', 'trust'], '{}', '{}', 'Within 4 months of year end', 'ASIC', 'https://asic.gov.au/for-business/your-business/lodging-your-documents/'),
  ('ASIC Annual Review', 'Complete your annual company review and pay the annual review fee to ASIC.', 'financial', 'annually', ARRAY['company'], '{}', '{}', 'Anniversary of registration', 'ASIC', 'https://asic.gov.au/for-business/your-business/starting-a-company/annual-review/'),
  ('Business Activity Statement Review', 'Review your BAS position quarterly and ensure records are accurate and up to date.', 'financial', 'quarterly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Quarterly review', 'Australian Taxation Office', NULL),
  ('Bank Account Reconciliation', 'Reconcile business bank accounts to ensure financial records are accurate.', 'financial', 'monthly', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Monthly', NULL, NULL);

-- Licensing & Permits
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('ABN Registration / Renewal', 'Ensure your Australian Business Number is current and details are accurate.', 'licensing', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Ongoing', 'Australian Business Register', 'https://www.abr.business.gov.au/'),
  ('Business Name Registration Renewal', 'Renew your registered business name with ASIC before expiry.', 'licensing', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Every 1 or 3 years from registration', 'ASIC', 'https://asic.gov.au/for-business/your-business/business-names/'),
  ('Industry-Specific Licence Renewal', 'Renew any industry-specific licences, permits, or registrations.', 'licensing', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['hospitality', 'construction', 'healthcare', 'finance', 'real_estate', 'transport', 'education'], 'Based on licence type', 'Various regulators', NULL),
  ('Food Safety Supervisor Certificate', 'Ensure at least one Food Safety Supervisor is nominated and certified for each food premises.', 'licensing', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['hospitality', 'retail'], 'Renew as required', 'State Food Authority', NULL);

-- Privacy & Data
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Privacy Policy Review', 'Review and update your privacy policy to comply with the Australian Privacy Principles.', 'privacy', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', '{}', 'Review annually', 'OAIC', 'https://www.oaic.gov.au/privacy/the-privacy-act'),
  ('Notifiable Data Breaches Assessment', 'Assess any data breaches against the Notifiable Data Breaches scheme requirements.', 'privacy', 'once', ARRAY['company', 'trust'], '{}', '{}', 'Within 30 days of breach', 'OAIC', 'https://www.oaic.gov.au/privacy/notifiable-data-breaches'),
  ('Customer Data Audit', 'Audit stored customer data to ensure compliance with privacy obligations and data retention policies.', 'privacy', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], '{}', ARRAY['retail', 'hospitality', 'healthcare', 'technology', 'professional_services', 'finance'], 'Annually', 'OAIC', 'https://www.oaic.gov.au/privacy/your-privacy-rights');

-- State-specific obligations
INSERT INTO compliance_rules (title, description, category, frequency, business_types, states, industries, default_due_date, authority, reference_url) VALUES
  ('Payroll Tax', 'Pay state payroll tax if total taxable wages exceed the threshold.', 'taxation', 'monthly', ARRAY['company', 'trust', 'partnership'], ARRAY['NSW', 'VIC', 'QLD', 'SA', 'WA', 'TAS', 'NT', 'ACT'], '{}', 'Monthly (or annually if under $100k)', 'State Revenue Office', NULL),
  ('Land Tax', 'Pay land tax on commercial property holdings exceeding the threshold.', 'taxation', 'annually', ARRAY['company', 'trust', 'partnership'], ARRAY['NSW', 'VIC', 'QLD', 'SA', 'WA', 'TAS', 'ACT'], '{}', 'Annual assessment', 'State Revenue Office', NULL),
  ('Fire Safety Certificate', 'Obtain or renew fire safety certificates for commercial premises.', 'safety', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], ARRAY['NSW', 'VIC', 'QLD', 'SA', 'WA', 'TAS', 'NT', 'ACT'], '{}', 'Annual compliance', 'State Fire Authority', NULL),
  ('Liquor Licence Renewal', 'Renew your liquor licence if you sell or serve alcohol.', 'licensing', 'annually', ARRAY['sole_trader', 'partnership', 'company', 'trust', 'cooperative'], ARRAY['NSW', 'VIC', 'QLD', 'SA', 'WA', 'TAS', 'NT', 'ACT'], ARRAY['hospitality', 'retail'], 'Annual renewal', 'State Liquor Authority', NULL);
